### ISSUE TITLE
TypeError: this.channel.sendMenu is not a function

### ISSUE THREAD

**Issue by Ole113** [Mundayne/reaction-core#12]
`TypeError: this.channel.sendMenu is not a function
    at C:\Users\\OneDrive\Documents\Programming\node_modules\reaction-menu\src\menu.js:18:22
    at new Promise (<anonymous>)
    at Menu.send (C:\Users\\OneDrive\Documents\Programming\\node_modules\reaction-menu\src\menu.js:14:12)
    at Object.exports.run (C:\Users\\OneDrive\Documents\Programming\\commands\help.js:88:14)`

Happened when I upgraded from v11 to v12.

**Comment by Mundayne** [comment]
This error is caused due to reaction-core not supporting sending menus in DMs. This has been fixed in v2.4.0. Note that due to Discord's API limitations, users reactions are not removed in DMs, so the user will have to manually remove their own reactions if that is needed.
